#pragma once

namespace katalysti
{
    namespace character
    {
        constexpr std::array<const char*, 20> DWARF_FIRST_NAME
        {
            "Dingog",
            "Kruluagg",
            "Burhogrig",
            "Theldahm",
            "Urdos",
            "Ormehr",
            "Khakother",
            "Guhdrikos",
            "Emdus",
            "Brunar",
            "Ravaidoss",
            "Gweidanla",
            "Aezos",
            "Owhime",
            "Unga",
            "Meathoten",
            "Thangennon",
            "Ushe",
            "Bruda",
            "Tave"
        };
        constexpr std::array<const char*, 20> DWARF_LAST_NAME
        {
            "Kindroar",
            "Truerest",
            "Firsttale",
            "Flintforce",
            "Drunkbreaker",
            "Icefield",
            "Mountaincave",
            "Laststand",
            "Shorthorn",
            "Shorthonor",
            "Longbeard",
            "Sternfeast",
            "Frozenshield",
            "Onyxfall",
            "Iceboots",
            "Strongboot",
            "Stonegame",
            "Steelbreath",
            "Wildmantle",
            "Goldenback"
        };
        constexpr std::array<const char*, 20> UNDEAD_FIRST_NAME
        {
            "Stephan",
            "Cretien",
            "Granville",
            "Dillen",
            "Gaige",
            "Stein",
            "Seppel",
            "Durante",
            "Deston",
            "Kory",
            "Cheyanna",
            "Stella",
            "Marquisha",
            "Ashli",
            "Frances",
            "Maelee",
            "Walburge",
            "Ezra",
            "Katarina",
            "Conrada"
        };
        constexpr std::array<const char*, 20> UNDEAD_LAST_NAME
        {
            "Nightfeast",
            "Shallowflight",
            "Plaguebane",
            "Shallowhold",
            "Shadowthrill",
            "Weiss",
            "Nebula",
            "Riley",
            "Hamilton",
            "Call",
            "Cursewill",
            "Lightdestroyer",
            "Falsemeat",
            "Scourgespark",
            "Slimroad",
            "Dred",
            "Vome",
            "Chester",
            "Lightspell",
            "Townend"
        };
        constexpr std::array<const char*, 20> ORC_FIRST_NAME
        {
            "Sorgarm",
            "Herzirgoth",
            "Solzus",
            "Zur",
            "Merl",
            "Thugnothek",
            "Gravtosh",
            "Kottoz",
            "Krondutel",
            "Asdu",
            "So'tini",
            "Shodremu",
            "Gimava",
            "Ankahnir",
            "Gigvetga",
            "Ary",
            "Shulizit",
            "Sahmi",
            "Gertit",
            "Mogo"
        };
        constexpr std::array<const char*, 20> ORC_LAST_NAME
        {
            "Broadaxe",
            "Vengepack",
            "Stormlaugh",
            "Wrathtwist",
            "Lonesnarl",
            "Warrunner",
            "Frostbone",
            "Stronghorn",
            "Deepscream",
            "Blacksorrow",
            "Warwind",
            "Keencrusher",
            "Blackfury",
            "Burningmaul",
            "Grimblood",
            "Stoutfist",
            "Coldhunt",
            "Strongslayer",
            "Shadowsteel",
            "Boldshift"
        };
    }
}